server:
  port: 8082

spring:
  jackson:
    serialization:
      indent_output: true

ontop:
  endpoint: ${ONTOP_ENDPOINT:http://localhost:8080/sparql}
  default-accept: application/sparql-results+json

wikidata:
  api-url: ${WIKIDATA_API_URL:https://www.wikidata.org/w/api.php}
  language: ${WIKIDATA_LANGUAGE:en}
