// central tuning knobs + the map of app-relative api routes; imported everywhere so numbers live in one place
export const APP_CONFIG = {
  autocomplete: {
    threshold: 0.2,
    maxResults: 8,
  },
  query: {
    pageSize: 10,
    defaultLimit: 150,
  },
  history: {
    maxEntries: 50,
    cookieMax: 10,
    cookieQueryLimit: 200,
    cookieMaxAgeDays: 30,
  },
  similarity: {
    defaultThreshold: 0.5,
    startsWithBonus: 0.3,
    substringBonus: 0.2,
    pairScore: {
      sharedId: 1.0,
      sameName: 0.9,
      minDisplay: 0.05,
    },
  },
  api: {
    // spring backend base; overridden per-deploy via env, localhost for dev
    backendUrl: process.env.BACKEND_URL ?? "http://localhost:8082",
    // next api-route paths the frontend calls; most just proxy through to backendUrl
    routes: {
      sparql:               "/api/sparql",
      nlp:                  "/api/nlp",
      substances:           "/api/substances",
      substancesDetails:    "/api/substances/details",
      substancesCrossSource:"/api/substances/cross-source",
      substancesQuickSearch:        "/api/substances/quick-search",
      substancesQuickSearchBackend: "/api/substances/quick-search",
      similarityPair:       "/api/similarity/elh/pair",
      similarityTopK:       "/api/similarity/elh/topk",
      similarityExpand:     "/api/similarity/elh/expand-sparql",
      similarityConcepts:   "/api/similarity/elh/concepts",
      similarityExplain:    "/api/similarity/elh/explain",
      authLogin:            "/api/auth/login",
      authRegister:         "/api/auth/register",
      authLogout:           "/api/auth/logout",
      authMe:               "/api/auth/me",
      me:                   "/api/me",
      mePassword:           "/api/me/password",
      mePreferences:        "/api/me/preferences",
      bookmarks:            "/api/bookmarks",
      sandbox:              "/api/sandbox",
      sandboxUpload:        "/api/sandbox/upload",
      sandboxStatus:        "/api/sandbox/status",
      sandboxQuery:         "/api/sandbox/query",
      sandboxSave:          "/api/sandbox/save",
      profileConfig:        "/api/profile/config",
      profileConfigRestore: "/api/profile/config/restore",
      wikidata:             "/api/wikidata",
      wikidataBackend:      "/api/enrichment/wikidata/search",
      admin:                "/api/admin",
      cacheClear:           "/api/cache/clear",
    },
  },
} as const;
